### ISSUE TITLE
Comma missing in the BibTex citation

### ISSUE THREAD

**Issue by jellevos** [wenbihan/coverage#1]
The BibTex citation in the `readme.md` gives an error as it is expecting an extra comma.  There is also an extra year field. The citation is also missing on https://ieeexplore.ieee.org/document/7532339/. May I suggest changing the citation to:

```
@inproceedings{wen2016coverage,
  author={Wen, Bihan and Zhu, Ye and Subramanian, Ramanathan and Ng, Tian-Tsong and Shen, Xuanjing and Winkler, Stefan},
  title={COVERAGE – A NOVEL DATABASE FOR COPY-MOVE FORGERY DETECTION},
  year={2016},
  booktitle={IEEE International Conference on Image processing (ICIP)},
  pages={161--165}
}
```

**Comment by wenbihan** [comment]
Nice catch! The Bibtex citation has been fixed.
Thank you!
